task_id:"mEgHHupdjEXJB2AHR3RGf" situation_id:"rwi60MbQW7WczuMuDHR55" check_item:{check_item_id:"XHwSnS8EqSioA1euY-Qnx" command:{command_id:"BwTLb8GUKpoUftQLtLFBB" command_line:"progate diagnose"}} check_item:{check_item_id:"8WeHJd_cU-tzAYYufmd1h" command:{command_id:"cbdQEl4AC03yUDasHRPao" command_line:"npm run typecheck"} command:{command_id:"PeSK5kRWsOKG5WmX3JcEl" command_line:"npm run lint:check"}}