task_id:"_z2u45qMAiAoBj8qo5uDH" situation_id:"AIVX0qOzkk8h7BHbbeHDX" check_item:{check_item_id:"51mfY0_Qk83UJ5e6EVYFx" command:{command_id:"JqRDStVcfc01hbPHRmY-w" command_line:"progate diagnose"}} check_item:{check_item_id:"vAUXnYtGtnGSi6UsBDqkx" command:{command_id:"YJE9cUYmCCccV8N8qQldY" command_line:"npm run lint:check"} command:{command_id:"R5gnuamrYfTAeCBSfeGbH" command_line:"npm run format:check"}}