task_id:"HjVfSyYuBHm2KAbFFeqRx" situation_id:"R74o7v94PexU0dkqnJwz7" check_item:{check_item_id:"MuAEkayF73gzKoQy8TG2A" command:{command_id:"iyw-6K0fPhFQZNuo0ypNN" command_line:"progate diagnose"}} check_item:{check_item_id:"zFY43e6I8EMIGPz7Ke2aN" command:{command_id:"ST1vtXVfGO6U3AiuOpKDL" command_line:"npm run typecheck"} command:{command_id:"IylhxQy6cvXFf8cdLZ0RC" command_line:"npm run lint:check"}}