task_id:"a77wIrjQkwdQIDcGhW897" situation_id:"E-wkmqGsTVjou1mF7T9KX" check_item:{check_item_id:"Qm9n36FxxStT0Qk55RVUZ" command:{command_id:"v08nHCCBZLv7mjqDtIfm0" command_line:"progate diagnose"}} check_item:{check_item_id:"IrAxLBEwaAAWaMh4ILE2q" command:{command_id:"mf5JZRCniF1mvK4zNA2VM" command_line:"npm run typecheck"} command:{command_id:"7J9wSj3aKn8fZ4vPV9JiY" command_line:"npm run lint:check"}}