task_id:"zBzJmrg5gkB9M2YLaCfHz" situation_id:"WkN9LGX6A3pCrptvX7GuN" check_item:{check_item_id:"oZmv6sSW9p5p4r1Ku541t" command:{command_id:"SyAowP1N7ZakH9RTMNv1q" command_line:"progate diagnose"}} check_item:{check_item_id:"ecf9i4AGtOm9spw6KH5AU" command:{command_id:"Z5zoCUO0XtgWO31hTqOyc" command_line:"npm run format:fix"} command:{command_id:"94o1UtzVA-Qav1rtCJNc2" command_line:"npm run format:check"}}