task_id:"U3NYOzd5cZdzzZwTG7HXQ" situation_id:"6XScDp83GlTarUt56ZZHG" check_item:{check_item_id:"oiUuI9OOhyscYKXlHO0Yj" command:{command_id:"Au3bnCSuVBTqpw1vSDvoY" command_line:"progate diagnose"}} check_item:{check_item_id:"IVoTeNDoWGAL5aXSzNAfT" command:{command_id:"zjp5zYK9K8enIkYA62y9O" command_line:"npm run typecheck"} command:{command_id:"CaVLvjyBkU2Td7iKdbkvE" command_line:"npm run lint:check"}}